---

- name: Prep for OpenShift install 
  hosts: ocp 
  tasks: 



    - name: deploy authorized_key
      authorized_key:
        user: root 
        state: present
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKR8cYLVjcMggV/a0g4GTBgCUbcNihlytm80nLMO7fGzMIpgezs6wJJZmWOuIW4doh+ciBZEIaDDMkaGWHZC8uAyl2aOpjQrwvYnKF6FqeIG51qfvDK61S7Mex8yHHQyfSpzQafT7JKq6t+kNuTq5J+oiSVd4xBgbtTfF0TTiilIlxqWQYdGOanLLpfWdEucMmKzEoAzJ3WigHyyYVyWCxkou1i+tTJXE/yH4Leh0rjDCF66huQrK8jcKBUxXBI6DoP1zZCp2rzqXyAFtX1svaHz/FloPp5va8R+pPpqXoQSr3qfZ5c/wvWo1ve/JHU4+LQkuGLhF1EAROeCJ64VkZ root_public_key'


    - name: add motd
      copy:
        dest: /etc/motd
        src: ./motd

    - name: update system
      yum:
        name: "*"
        state: latest


    - name: install needed packges 
      yum:
        name:
          - wget
          - git
          - net-tools
          - bind-utils
          - iptables-services
          - bridge-utils
          - bash-completion
          - kexec-tools
          - sos
          - psacct 
          - docker
          - PyYAML
        state: latest
        

    - name: update docker config
      copy:
        src: sysconfig_docker
        dest: /etc/sysconfig/docker
        backup: yes


    - name: start and enable docker
      service:
        name: docker
        state: started
        enabled: yes
